#pragma once

#define __VK_EX(x) ((signed int)-(x))
#define __VK_FN(x) (0x5B5B1B | (((x) - 1 + 'A') << 24))
#define __VK_PD(x) (0x7E005B1B | (((x) + '0') << 16))
#define __VK_AR(x) (0x5B1B | (((x) - 1 + 'A') << 16))

#define   VK_EOF        __VK_EX(1)
#define   VK_SHIFT 	__VK_EX(2)
#define   VK_RSHIFT 	__VK_EX(3)
#define   VK_CTRL 	__VK_EX(4)
#define   VK_RCTRL 	__VK_EX(5)
#define   VK_ALT 	__VK_EX(6)
#define   VK_RALT 	__VK_EX(7)
#define   VK_CAPS 	__VK_EX(8)
#define   VK_MENU 	__VK_EX(9)
#define   VK_WIN 	__VK_EX(10)
#define   VK_F1 	__VK_FN(1)
#define   VK_F2 	__VK_FN(2)
#define   VK_F3 	__VK_FN(3)
#define   VK_F4 	__VK_FN(4)
#define   VK_F5 	__VK_FN(5)
#define   VK_F6 	__VK_FN(6)
#define   VK_F7 	__VK_FN(7)
#define   VK_F8 	__VK_FN(8)
#define   VK_F9 	__VK_FN(9)
#define   VK_F10 	__VK_FN(10)
#define   VK_F11 	__VK_FN(11)
#define   VK_F12 	__VK_FN(12)
#define   VK_HOME 	__VK_PD(1)
#define   VK_INS 	__VK_PD(2)
#define   VK_DEL 	__VK_PD(3)
#define   VK_END 	__VK_PD(4)
#define   VK_PGUP 	__VK_PD(5)
#define   VK_PGDN 	__VK_PD(6)
#define   VK_UP 	__VK_AR(1)
#define   VK_DOWN 	__VK_AR(2)
#define   VK_RIGHT 	__VK_AR(3)
#define   VK_LEFT 	__VK_AR(4)
//  all the above should be in the slot of ich_t
